version: "3"
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"
  web:
    image: mbyakow/visits-counter
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "49160:80"
    links:
      - db
    networks:
      - webnet
networks:
  webnet: