version: "3"
services:
  db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"
  web:
    container_name: app
    image: mbyakow/visits-counter
    restart: always
    build: .
    environment:
      - NODE_ENV=production
      - TEST_COUNT_ONLY_UNIQUE=false
    ports:
      - "8000:8000"
    links:
      - db